### PR TITLE
Add a --no-download flag to avoid fetching crates

### PR DESCRIPTION
**Pull request by stevenjm**
In theory, cargo-bootstrap would previously have worked in no-download
mode, as long as all of the versions installed are the latest versions
in the crates index. For use in a networkless environment, or a package
build system that needs to be usable without networking, it's sometimes
useful to have a set of pre-downloaded crates that satisfy dependencies
without being the latest versions available.

This commit adds a --no-download flag which forces cargo-bootstrap to
look only for locally downloaded versions of crates, and fail if a
dependency cannot be resolved that way.

This is a reworked version of https://github.com/dhuseby/cargo-bootstrap/pull/7, with the following main differences:
- it uses cargo-bootstrap's Semver class instead of Python's LooseVersion;
- it splits out the crate-finding logic into a separate function for cleanliness;
- it actually checks to make sure the available crates' versions satisfy dependencies.

### CODE REVIEW

**Comment by dhuseby** [comment]
@stevenjm  can you rebase this for me?  I'll land it then.

**Comment by dhuseby** [comment]
@stevenjm I'm still waiting for a rebase.

**Comment by stevenjm** [comment]
Sorry, I just got around to this now. It appears to have already been manually merged as ed1ed377a97d9dbef26883e2928867acc5f7f630 by @krig, prior to the changes that created the conflicts. I'll close this PR.

**Comment by dhuseby** [comment]
Great! Thanks

**Pull request closed without merging**
